import Head from 'next/head';
import Gallery from '../components/Gallery';

export default function Home() {
	return (
		<>
			<Head>
				<title>Liquid Scroll | Curtains.js | Nishit Sarvaiya</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Gallery />
			</main>
		</>
	);
}
